import { Product } from './types'

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Sentinel Pro 4K',
    modelId: 'HDS-SNT-4K-001',
    manufacturingId: 'MFG-SNT-4K-001',
    brand: 'Hawking Defence',
    price: 2499,
    originalPrice: 2999,
    image: '/images/drone-sentinel-pro.png',
    category: 'Professional Drones',
    subcategory: 'Surveillance',
    rating: 4.8,
    reviews: 342,
    inStock: true,
    stock: 50,
    description: 'Advanced surveillance drone with 4K thermal imaging',
    longDescription:
      'The Sentinel Pro 4K is engineered for professional surveillance and reconnaissance missions. Featuring dual-spectrum thermal and visible-light sensors, it delivers crystal-clear imagery in any lighting condition. Built for defense contractors, law enforcement, and industrial security teams who require reliable, all-weather performance with encrypted data transmission.',
    specs: {
      'Flight Time': '45 minutes',
      'Max Speed': '75 km/h',
      'Range': '8 km',
      'Camera': '4K Thermal + 20MP RGB',
      'Wind Resistance': '50 km/h',
      'Weight': '1.8 kg',
      'Dimensions': '38 × 38 × 12 cm (folded)',
      'Operating Temp': '-20°C to 50°C',
      'Battery': '6000 mAh LiPo',
      'Transmission': 'OcuSync 3.0 Encrypted',
    },
    features: [
      'Thermal imaging technology with 640×512 resolution',
      '45-minute flight time with swappable batteries',
      '360° obstacle avoidance system',
      'IP65 waterproof and dust-resistant design',
      'Military-grade AES-256 data encryption',
      'Auto-return and low-battery failsafe',
      'Night vision and low-light enhancement',
      'Live HD video streaming up to 8 km',
    ],
    images: ['/images/drone-sentinel-pro.png'],
    inTheBox: [
      'Sentinel Pro 4K Drone',
      'Remote Controller with 7" Display',
      '2× Intelligent Flight Batteries',
      'Battery Charging Hub',
      'Propeller Set (spare)',
      'Carrying Case',
      'USB-C Cable & Power Adapter',
      'Quick Start Guide',
    ],
    warranty: {
      duration: '2 Years',
      type: 'Manufacturer Limited Warranty',
      coverage: [
        'Manufacturing defects in materials and workmanship',
        'Motor and flight controller failures',
        'Camera and gimbal malfunctions',
        'Free firmware updates for warranty period',
      ],
      exclusions: [
        'Crash damage from pilot error',
        'Water damage beyond IP65 rating',
        'Unauthorized modifications or repairs',
        'Normal wear on propellers and landing gear',
      ],
      extendedAvailable: true,
      extendedPrice: '₹299/year',
    },
    reviewList: [
      {
        id: 'r1-1',
        author: 'Marcus T.',
        rating: 5,
        date: '2026-01-15',
        title: 'Outstanding thermal performance',
        comment:
          'Used this on a border patrol contract. Thermal imaging is crisp even at 500m altitude. Battery life matches specs.',
        verified: true,
      },
      {
        id: 'r1-2',
        author: 'Elena R.',
        rating: 5,
        date: '2025-12-08',
        title: 'Professional grade quality',
        comment:
          'Worth every penny. The encrypted transmission gives our team confidence during sensitive operations.',
        verified: true,
      },
      {
        id: 'r1-3',
        author: 'James K.',
        rating: 4,
        date: '2025-11-22',
        title: 'Great drone, steep learning curve',
        comment:
          'Feature-rich platform. Took a week to master all modes, but support team was very helpful.',
        verified: true,
      },
    ],
    shipping: {
      freeShipping: true,
      deliveryTime: '3–5 business days',
      regions: ['United States', 'Canada', 'EU', 'UK', 'Australia'],
    },
    support: {
      phone: '+1 (234) 567-890',
      email: 'support@hawking.com',
      documentation: 'https://docs.hawking.com/sentinel-pro-4k',
    },
  },
  {
    id: '2',
    name: 'Guardian X500',
    modelId: 'HDS-GRD-X500-002',
    manufacturingId: 'MFG-GRD-X500-002',
    brand: 'Hawking Defence',
    price: 1899,
    originalPrice: 2199,
    image: '/images/drone-guardian-x500.png',
    category: 'Professional Drones',
    subcategory: 'Mapping',
    rating: 4.7,
    reviews: 287,
    inStock: true,
    stock: 50,
    description: 'High-precision mapping drone for industrial applications',
    longDescription:
      'The Guardian X500 sets the standard for aerial surveying and 3D mapping. With integrated LiDAR and a 48MP RGB camera, it captures survey-grade data for construction, mining, and agriculture. RTK positioning ensures centimeter-level accuracy for professional GIS workflows.',
    specs: {
      'Flight Time': '38 minutes',
      'Max Speed': '68 km/h',
      'Range': '7 km',
      'Camera': '48MP RGB + LiDAR',
      'Accuracy': '±2 cm (RTK)',
      'Weight': '2.1 kg',
      'Dimensions': '42 × 42 × 14 cm (folded)',
      'Coverage': '120 hectares per flight',
      'Battery': '5200 mAh LiPo',
      'Data Format': 'LAS, GeoTIFF, OBJ',
    },
    features: [
      '48MP RGB camera with mechanical shutter',
      'Integrated LiDAR for 3D point clouds',
      'Autonomous grid flight planning',
      '38-minute endurance per battery',
      'IP67 waterproof rating',
      'PPK/RTK dual-frequency GNSS',
      'One-click orthomosaic processing',
      'Compatible with Pix4D and DroneDeploy',
    ],
    images: ['/images/drone-guardian-x500.png'],
    inTheBox: [
      'Guardian X500 Drone',
      'RTK Base Station',
      'Remote Controller',
      '3× Flight Batteries',
      'Multi-battery Charger',
      'LiDAR Calibration Target',
      'Hard Shell Transport Case',
      'Survey Software License (1 year)',
    ],
    warranty: {
      duration: '18 Months',
      type: 'Professional Equipment Warranty',
      coverage: [
        'LiDAR sensor and camera defects',
        'RTK module and GPS failures',
        'Airframe structural defects',
        'Software bug fixes and patches',
      ],
      exclusions: [
        'Calibration drift from improper storage',
        'Lens scratches from improper handling',
        'Third-party software compatibility issues',
        'Battery degradation after 300 cycles',
      ],
      extendedAvailable: true,
      extendedPrice: '₹249/year',
    },
    reviewList: [
      {
        id: 'r2-1',
        author: 'David L.',
        rating: 5,
        date: '2026-02-01',
        title: 'Survey-grade accuracy',
        comment:
          'Compared against ground survey — consistently within 2cm. LiDAR integration is seamless.',
        verified: true,
      },
      {
        id: 'r2-2',
        author: 'Priya S.',
        rating: 4,
        date: '2025-10-18',
        title: 'Solid mapping platform',
        comment:
          'Great for construction site monitoring. Software license is a nice bonus.',
        verified: true,
      },
    ],
    shipping: {
      freeShipping: true,
      deliveryTime: '4–6 business days',
      regions: ['United States', 'Canada', 'EU', 'India'],
    },
    support: {
      phone: '+1 (234) 567-890',
      email: 'mapping@hawking.com',
      documentation: 'https://docs.hawking.com/guardian-x500',
    },
  },
  {
    id: '3',
    name: 'Viper 3000 Elite',
    modelId: 'HDS-VPR-3K-003',
    manufacturingId: 'MFG-VPR-3K-003',
    brand: 'Hawking Defence',
    price: 1649,
    originalPrice: 1999,
    image: '/images/drone-viper-3000.png',
    category: 'Combat Drones',
    subcategory: 'Tactical',
    rating: 4.9,
    reviews: 512,
    inStock: true,
    stock: 50,
    description: 'Precision tactical drone for advanced operations',
    longDescription:
      'The Viper 3000 Elite is a compact tactical UAV designed for rapid deployment in field operations. Its modular payload bay supports reconnaissance cameras, signal relays, and custom mission equipment. Stealth-optimized airframe and low acoustic signature make it ideal for covert surveillance missions.',
    specs: {
      'Flight Time': '52 minutes',
      'Max Speed': '85 km/h',
      'Range': '10 km',
      'Payload': '5 kg modular bay',
      'Armament': 'Modular (non-lethal options)',
      'Weight': '1.4 kg (base)',
      'Dimensions': '35 × 35 × 10 cm (folded)',
      'Stealth': 'Low acoustic signature',
      'Deployment': '< 60 seconds',
      'Encryption': 'AES-256 + frequency hopping',
    },
    features: [
      'Advanced AI targeting and tracking',
      'Modular payload system (5 kg capacity)',
      '52-minute extended flight time',
      'Radar-absorbing stealth design',
      'Multi-sensor fusion (EO/IR/LRF)',
      'Hand-launch capable, no runway needed',
      'Mesh networking for swarm operations',
      'Ruggedized for -30°C to 55°C',
    ],
    images: ['/images/drone-viper-3000.png'],
    inTheBox: [
      'Viper 3000 Elite Airframe',
      'Tactical Hand Controller',
      '2× Extended Batteries',
      'Modular Payload Mount',
      'EO/IR Camera Module',
      'Field Repair Kit',
      'Pelican Transport Case',
      'Mission Planning Software',
    ],
    warranty: {
      duration: '3 Years',
      type: 'Tactical Equipment Warranty',
      coverage: [
        'Full airframe and avionics coverage',
        'Payload bay mechanism defects',
        'Controller and link system failures',
        'Priority replacement within 48 hours',
      ],
      exclusions: [
        'Combat or hostile environment damage',
        'Payload modules from third parties',
        'Loss of unit in operation',
        'Batteries after 200 charge cycles',
      ],
      extendedAvailable: true,
      extendedPrice: '₹399/year',
    },
    reviewList: [
      {
        id: 'r3-1',
        author: 'Col. Anderson',
        rating: 5,
        date: '2026-01-28',
        title: 'Mission-ready out of the box',
        comment:
          'Deployed in under a minute in field tests. Tracking performance exceeded expectations.',
        verified: true,
      },
      {
        id: 'r3-2',
        author: 'Ravi M.',
        rating: 5,
        date: '2025-12-14',
        title: 'Best tactical UAV in class',
        comment:
          'Modular payload system is a game changer. Swapped camera module in the field without tools.',
        verified: true,
      },
      {
        id: 'r3-3',
        author: 'Tom H.',
        rating: 5,
        date: '2025-09-30',
        title: 'Exceptional endurance',
        comment: '52 minutes real-world flight time with full payload. Impressive engineering.',
        verified: true,
      },
    ],
    shipping: {
      freeShipping: true,
      deliveryTime: '5–7 business days (verified accounts)',
      regions: ['Government & verified defense contractors only'],
    },
    support: {
      phone: '+1 (234) 567-891',
      email: 'tactical@hawking.com',
      documentation: 'https://docs.hawking.com/viper-3000',
    },
  },
  {
    id: '4',
    name: 'Aurora Reconnaissance',
    modelId: 'HDS-AUR-ISR-004',
    manufacturingId: 'MFG-AUR-ISR-004',
    brand: 'Hawking Defence',
    price: 3299,
    originalPrice: 3999,
    image: '/images/drone-aurora.png',
    category: 'Military Grade',
    subcategory: 'ISR',
    rating: 4.9,
    reviews: 189,
    inStock: true,
    stock: 50,
    description: 'Intelligence, Surveillance & Reconnaissance drone',
    longDescription:
      'The Aurora Reconnaissance platform represents the pinnacle of ISR technology. Equipped with an 8K multi-spectral camera suite and full-spectrum sensors, it operates at altitudes up to 5,000 meters. Designed for military intelligence units and critical infrastructure protection with classified-grade data handling.',
    specs: {
      'Flight Time': '60 minutes',
      'Max Speed': '95 km/h',
      'Range': '15 km',
      'Camera': '8K ISR Multi-Spectral Suite',
      'Altitude': '5000 m max',
      'Weight': '3.2 kg',
      'Sensors': 'EO, IR, UV, Hyperspectral',
      'Encryption': 'FIPS 140-2 Level 3',
      'Data Link': 'SATCOM + LOS dual',
      'Endurance Mode': '72 min (reduced payload)',
    },
    features: [
      '8K ISR camera suite with 30× zoom',
      'Full spectrum sensing (EO/IR/UV)',
      '60-minute standard endurance',
      'Fully autonomous waypoint navigation',
      'Classified data encryption (FIPS 140-2)',
      'SATCOM backup for beyond-line-of-sight',
      'AI threat detection and alerting',
      'NATO STANAG 4586 compatible',
    ],
    images: ['/images/drone-aurora.png'],
    inTheBox: [
      'Aurora ISR Airframe',
      'Ground Control Station (GCS)',
      '4× High-Capacity Batteries',
      '8K ISR Camera Module',
      'SATCOM Antenna Kit',
      'Encrypted Data Storage Unit',
      'MIL-SPEC Transport Case',
      'Operator Training Access (online)',
    ],
    warranty: {
      duration: '5 Years',
      type: 'Military Grade Service Agreement',
      coverage: [
        'Complete platform hardware coverage',
        'Sensor suite calibration annually',
        '24/7 priority technical support',
        'On-site repair for qualified accounts',
        'Firmware and security patch updates',
      ],
      exclusions: [
        'Hostile fire or combat damage',
        'Export control violations',
        'Unauthorized firmware modifications',
        'Operation outside certified parameters',
      ],
      extendedAvailable: false,
    },
    reviewList: [
      {
        id: 'r4-1',
        author: 'Intel Unit 7',
        rating: 5,
        date: '2026-02-10',
        title: 'ISR capability unmatched',
        comment:
          '8K imagery at altitude is remarkable. SATCOM link maintained connectivity at 12km.',
        verified: true,
      },
      {
        id: 'r4-2',
        author: 'Sarah W.',
        rating: 5,
        date: '2025-11-05',
        title: 'Enterprise-grade platform',
        comment:
          'Used for critical infrastructure monitoring. AI threat detection flagged issues we missed.',
        verified: true,
      },
    ],
    shipping: {
      freeShipping: true,
      deliveryTime: '7–14 business days (security clearance required)',
      regions: ['NATO member nations', 'Approved allied forces'],
    },
    support: {
      phone: '+1 (234) 567-892',
      email: 'isr@hawking.com',
      documentation: 'https://docs.hawking.com/aurora-isr',
    },
  },
  {
    id: '5',
    name: 'Falcon Scout Lite',
    modelId: 'HDS-FCN-LTE-005',
    manufacturingId: 'MFG-FCN-LTE-005',
    brand: 'Hawking Defence',
    price: 799,
    originalPrice: 999,
    image: '/images/drone-falcon-lite.png',
    category: 'Consumer Drones',
    subcategory: 'Entry Level',
    rating: 4.6,
    reviews: 1203,
    inStock: true,
    stock: 50,
    description: 'Affordable entry-level drone for beginners',
    longDescription:
      'The Falcon Scout Lite makes aerial photography accessible to everyone. This lightweight, foldable drone features intuitive one-touch controls, AI subject tracking, and a 2K camera perfect for travel and outdoor adventures. Ideal for hobbyists, content creators, and first-time drone pilots.',
    specs: {
      'Flight Time': '25 minutes',
      'Max Speed': '50 km/h',
      'Range': '3 km',
      'Camera': '2K FHD (1080p/60fps)',
      'Weight': '250 g',
      'Dimensions': '18 × 12 × 6 cm (folded)',
      'Gimbal': '2-axis mechanical',
      'Storage': 'MicroSD up to 256GB',
      'Registration': 'Under 250g — no license in most regions',
      'Charging': 'USB-C, 90 min full charge',
    },
    features: [
      'Ultra-compact foldable design',
      '25-minute flight time',
      'Beginner-friendly one-touch takeoff',
      '2K camera with 2-axis gimbal',
      'AI subject tracking (people, vehicles)',
      'QuickShots automated flight modes',
      'Find My Drone GPS locator',
      'Voice control via mobile app',
    ],
    images: ['/images/drone-falcon-lite.png'],
    inTheBox: [
      'Falcon Scout Lite Drone',
      'Compact Remote Controller',
      '1× Flight Battery',
      'USB-C Charging Cable',
      'Spare Propellers (4 pcs)',
      'Propeller Guards',
      'Soft Carrying Pouch',
      'Quick Start Guide & App QR Code',
    ],
    warranty: {
      duration: '1 Year',
      type: 'Standard Consumer Warranty',
      coverage: [
        'Manufacturing defects',
        'Motor and electronics failures',
        'Gimbal malfunction',
        '90-day hassle-free return',
      ],
      exclusions: [
        'Crash and impact damage',
        'Lost or flyaway incidents',
        'Water damage',
        'Propeller and consumable parts',
      ],
      extendedAvailable: true,
      extendedPrice: '₹79/year',
    },
    reviewList: [
      {
        id: 'r5-1',
        author: 'Amy C.',
        rating: 5,
        date: '2026-01-20',
        title: 'Perfect first drone',
        comment:
          'Bought for travel vlogging. Fits in my backpack and footage looks great for the price.',
        verified: true,
      },
      {
        id: 'r5-2',
        author: 'Chris B.',
        rating: 4,
        date: '2025-12-02',
        title: 'Great value, wish battery lasted longer',
        comment:
          'Easy to fly, AI tracking works well. 25 min is enough for most sessions but I bought a spare battery.',
        verified: true,
      },
      {
        id: 'r5-3',
        author: 'Nina P.',
        rating: 5,
        date: '2025-10-15',
        title: 'Kids love it',
        comment: 'Got this for my teenager. Propeller guards give peace of mind. Very intuitive app.',
        verified: true,
      },
      {
        id: 'r5-4',
        author: 'Leo F.',
        rating: 4,
        date: '2025-09-08',
        title: 'Solid entry-level option',
        comment: 'Good image quality for 2K. Wind handling could be better but acceptable at this price.',
        verified: false,
      },
    ],
    shipping: {
      freeShipping: true,
      deliveryTime: '2–4 business days',
      regions: ['Worldwide (120+ countries)'],
    },
    support: {
      phone: '+1 (234) 567-890',
      email: 'consumer@hawking.com',
      documentation: 'https://docs.hawking.com/falcon-scout-lite',
    },
  },
  {
    id: '6',
    name: 'Phoenix Heavy Lift',
    modelId: 'HDS-PHX-HL-006',
    manufacturingId: 'MFG-PHX-HL-006',
    brand: 'Hawking Defence',
    price: 4499,
    image: '/images/drone-phoenix.png',
    category: 'Industrial',
    subcategory: 'Cargo',
    rating: 4.8,
    reviews: 145,
    inStock: true,
    stock: 50,
    description: 'Heavy-lift cargo drone for logistics operations',
    longDescription:
      'The Phoenix Heavy Lift revolutionizes last-mile logistics with a 25 kg payload capacity and hybrid-electric propulsion. Designed for warehouse-to-door delivery, medical supply transport, and industrial parts delivery in remote areas. Autonomous flight planning and RTK precision landing ensure reliable operations.',
    specs: {
      'Flight Time': '35 minutes (full payload)',
      'Max Speed': '60 km/h',
      'Range': '6 km',
      'Payload': '25 kg max',
      'Power': 'Hybrid electric + range extender',
      'Weight': '8.5 kg (empty)',
      'Dimensions': '120 × 120 × 45 cm',
      'Landing': 'RTK precision ±5 cm',
      'Cargo Bay': '60 × 40 × 30 cm',
      'Weather': 'IP54, light rain capable',
    },
    features: [
      '25 kg payload capacity',
      'Hybrid-electric propulsion system',
      'Fully autonomous delivery routes',
      'IP54 weather-resistant design',
      'GPS + RTK precision positioning',
      'Automated cargo release mechanism',
      'Fleet management dashboard',
      'Redundant flight control systems',
    ],
    images: ['/images/drone-phoenix.png'],
    inTheBox: [
      'Phoenix Heavy Lift Airframe',
      'Industrial Ground Station',
      '3× Hybrid Battery Packs',
      'Cargo Bay Module',
      'RTK Landing Pad',
      'Fleet Management Software License',
      'Installation & Training (on-site)',
      'Maintenance Toolkit',
    ],
    warranty: {
      duration: '3 Years',
      type: 'Industrial Equipment Warranty',
      coverage: [
        'Propulsion system and motors',
        'Flight controller and avionics',
        'Cargo release mechanism',
        'Annual inspection and calibration',
        'On-site support for first year',
      ],
      exclusions: [
        'Overload beyond 25 kg rating',
        'Operation in severe weather (IP54 limits)',
        'Unauthorized cargo modifications',
        'Commercial misuse outside spec',
      ],
      extendedAvailable: true,
      extendedPrice: '₹599/year',
    },
    reviewList: [
      {
        id: 'r6-1',
        author: 'LogiCorp Inc.',
        rating: 5,
        date: '2026-01-08',
        title: 'Transformed our delivery ops',
        comment:
          'Deployed 6 units for warehouse deliveries. 25kg capacity handles 90% of our packages.',
        verified: true,
      },
      {
        id: 'r6-2',
        author: 'Dr. Kim Y.',
        rating: 5,
        date: '2025-11-20',
        title: 'Medical supply transport',
        comment:
          'Using for rural clinic deliveries. RTK landing is precise even in tight spaces.',
        verified: true,
      },
      {
        id: 'r6-3',
        author: 'Warehouse Ops',
        rating: 4,
        date: '2025-08-12',
        title: 'Powerful but needs space',
        comment:
          'Excellent payload capacity. Requires dedicated landing zone — plan infrastructure accordingly.',
        verified: true,
      },
    ],
    shipping: {
      freeShipping: false,
      deliveryTime: '10–15 business days (white-glove install)',
      regions: ['United States', 'EU', 'UAE', 'Singapore', 'India'],
    },
    support: {
      phone: '+1 (234) 567-893',
      email: 'industrial@hawking.com',
      documentation: 'https://docs.hawking.com/phoenix-heavy-lift',
    },
  },
]

export const CATEGORIES = [
  { id: 'professional', name: 'Professional Drones', count: 8 },
  { id: 'military', name: 'Military Grade', count: 5 },
  { id: 'consumer', name: 'Consumer Drones', count: 12 },
  { id: 'industrial', name: 'Industrial', count: 4 },
  { id: 'combat', name: 'Combat Drones', count: 3 },
]

export const PRICE_RANGES = [
  { label: 'Under ₹500', min: 0, max: 500 },
  { label: '₹500 - 1,000', min: 500, max: 1000 },
  { label: '₹1,000 - 2,000', min: 1000, max: 2000 },
  { label: '₹2,000 - 3,000', min: 2000, max: 3000 },
  { label: 'Over ₹3,000', min: 3000, max: 999999 },
]

export const RATINGS = [
  { stars: 5, label: '5 Stars' },
  { stars: 4, label: '4 Stars & up' },
  { stars: 3, label: '3 Stars & up' },
]
